spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

nc:
  about: This is a simple notes CRUD application from Production
  welcome-message: Welcome to Spring Notes Application from Production

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always